### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by NelsonSantos** [nicolo-ottaviani/Xamarin.BindableProperty.Fody#1]
Hi,

I get a error on build my Xamarin Forms .Net Standard project:

> error : Fody/BindableProperty: ^^^ BindableProperty.Fody  --ERROR: Cannot detect Xamarin.Forms version from the .csproj file at ModuleWeaver.Execute()

My FodyWeavers.xml file looks like this:
`<?xml version="1.0" encoding="utf-8"?>
<Weavers>
  <PropertyChanged />
  <BindableProperty />
</Weavers>`

There is some step that I have missed?

Regards

**Comment by NelsonSantos** [comment]
Nope!

I have to write all the code to put my custom controls to work.

My xamarin.forms reference version in csproj is the same, like yours.

I didn't have time to fork and see if I can find a solution.

I don't now exactly how Fody plugins run to check for a fix. I need to understand how it works.

**Comment by TheTrainor** [comment]
I have no experience with Fody either. Hopefully @nicolo-ottaviani will update us because this looks like a huge time saver.

In the meantime, I wrote a small snippet for Visual Studio that saves writing all the boilerplate manually. [Heres the Gist](https://gist.github.com/TheTrainor/9726dcf8f24294d0d6a4b31986cadc10). Feel free to use it, the shortcut is 'bindprop'.

**Comment by nicolo-ottaviani** [comment]
Hi NelsonSantos,
Sorry for the delay. It seems like it cant find the PackageReference tag in csproj file. Could you please send your csproj file?

**Comment by NelsonSantos** [comment]
Hi @nicolo-ottaviani, here is the file!

Thanks for your help.

Regards

[EsMarca.zip](https://github.com/nicolo-ottaviani/Xamarin.BindableProperty.Fody/files/2510491/EsMarca.zip)

**Comment by nicolo-ottaviani** [comment]
Ok, for some reason your csproject file has no namespace in the first row. I will rewrite the code so that it doesn't rely on namespaces.

**Comment by TheTrainor** [comment]
Had another go with this after seeing the new update, unfortunately still getting the same error.

**Comment by nicolo-ottaviani** [comment]
What do you mean with "the same error"? The csproj error message is no more present in the code.

**Comment by TheTrainor** [comment]
Hmm, well I have updated to version 0.1.4 and still get this error message:

> error : Fody/BindableProperty: ^^^ BindableProperty.Fody --ERROR: Cannot detect Xamarin.Forms version from the .csproj file at ModuleWeaver.Execute()

Have tried reinstalling from nuget, restarting VS, etc.

**Comment by nicolo-ottaviani** [comment]
weird :-D.  Look like a local cache issue. I have downloaded and decompiled the 0.1.4 nuget package and it doesn't contain that string anymore.

**Comment by TheTrainor** [comment]
You are right, after trying on my desktop it works perfectly fine. Thanks! Works like a charm and saves a lot of time!
