### ISSUE TITLE
Invalid IL Code exception

### ISSUE THREAD

**Issue by SimonRev** [nicolo-ottaviani/Xamarin.BindableProperty.Fody#2]
Don't want to discourage you, since I think that this weaver will soon be my favorite.  But unfortunately it didn't work for me:  Runtime error during type initialization:

![image](https://user-images.githubusercontent.com/19306211/47819482-43252580-dd20-11e8-988f-caf4cd7aabe6.png)

`    [XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class RfIconButton : RfButton
	{

        public RfIconButton()
        {
            IconAreaBackgroundColor = Color.Green;
            BackgroundColor = Color.Yellow;
            TextColor = Color.Red;
            FontSize = 12;
            Text = "Sample Text";
            InitializeComponent();
        }

        [Bindable]
        public Color IconAreaBackgroundColor { get; set; }

        [Bindable]
        public string Text { get; set; }

        [Bindable]
        public Color TextColor { get; set; }

        [Bindable]
        public double FontSize { get; set; }

        [Bindable]
        public ImageSource IconSource { get; set; }
    }`

**Comment by nicolo-ottaviani** [comment]
Thank you for your feedback. I think the problem is the Color properties. The problem is on finding the default value for structs. I am investigating on this.

**Comment by nicolo-ottaviani** [comment]
Ok, i have updated the IL so that now it supports struct-typed properties. I tested it with int, double, and Color properties and works. However some in-depth testing may be needed to cover all scenarios. I will do it in the next few days (now it's holidays in Italy).

**Comment by SimonRev** [comment]
Thanks man.  Looking forward to the update.

**Comment by nicolo-ottaviani** [comment]
Hi, the update is online already. There is a new version of the nuget package too

**Comment by SimonRev** [comment]
Hrm, I don't see anything newer than 0.1.4 no [nuget.org](https://www.nuget.org/packages/BindableProperty.Fody/).  

I would prefer to consume this as a nuget, although I am tempted to check the code out and see if I can figure out how to change the nuget to actually include the DLL into the project (like PropertyChanged.Fody), so I can use the BindableAttribute class that you provided, and then issue a pull request if I can get than straightened out.

**Comment by nicolo-ottaviani** [comment]
Ops, you are right. I messed up with version numbering. I am publishing the correct 0.1.5 nuget package. Keep in mind that you can use ANY BindableAttribute class, not just the one provided. Just define it in your code, like this: 
    [AttributeUsage(AttributeTargets.Property)]
    public class BindableAttribute : Attribute { }

**Comment by SimonRev** [comment]
Works great!  Thanks.
