### ISSUE TITLE
Fails when the type of the property to be bound is a generic type

### ISSUE THREAD

**Issue by SimonRev** [nicolo-ottaviani/Xamarin.BindableProperty.Fody#3]
Something doesn't work when the type in question is a generic type.
`

    public class NonSelectableListView : ContentView
	{
        // Note:  We are using IEnumerable<object> instead of IEnumerable for the ItemSource type to permit certain LINQ expressions more easily.  We could consider going up to an 
        // IList which might be even better and have a Count property that doesn't require enumerating the list to calculate.
        public static readonly BindableProperty ItemsSourceProperty = BindableProperty.Create(nameof(ItemsSource), typeof(IEnumerable<object>),
            typeof(NonSelectableListView), propertyChanged: OnItemsSourceChanged);

        public IEnumerable<object> ItemsSource
        {
            get => (IEnumerable<object>)GetValue(ItemsSourceProperty);
            set => SetValue(ItemsSourceProperty, value);
        }
`

**Comment by nicolo-ottaviani** [comment]
Thanks for the feedback. Now i have some spare time, i am investigating on the issue.

**Comment by nicolo-ottaviani** [comment]
Now this should be fixed with version 0.1.6
