### ISSUE TITLE
No weavers found for the configuration entries BindableProperty.

### ISSUE THREAD

**Issue by jasekiw** [nicolo-ottaviani/Xamarin.BindableProperty.Fody#5]
Got this error after adding the nuget package and building.

```
No weavers found for the configuration entries BindableProperty. 
Add the desired weavers via their nuget package; see https://github.com/Fody/Fody/wiki
on how to migrate InSolution, custom or legacy weavers.
```
I am using PropertyChanged.Fody package just fine but this package just throws that error.
I wonder if it is a problem with the version of Fody>

**Comment by jasekiw** [comment]
I cloned your repo and found that your solution is set up differently than mine. 

Mine has a C# project where the xamarin forms are stored and I installed the nuget package there. Yours has a shared project for the xamarin forms and has the package installed for Android and IOS.

I would like to build my xamarin forms seperately which a shared project doesn't support. How can I include this for my xamarin forms project?

**Comment by nicolo-ottaviani** [comment]
Sorry for the late response.
I hope you solved the issue. In any case, the best way to embed the project in you code is via the NuGet package. You can build your own NuGet package or download it from nuget.org. In this case, it is irrilevant if the project is in SharedProject or PortableLibrary mode.
